### PR TITLE
fix(s3): allow anonymous access when PublicAccessBlock config is miss…

### LINKED ISSUE #2036: Custom policy ignored after upgrade to Alpha 84
**Describe the bug**
I have set a custom bucket policy for Mastodon, anonymous read shall be allowed, so profile pictures and media can be displayed.

This is the policy from the [Mastodon docs](https://docs.joinmastodon.org/admin/optional/object-storage/#minio), it works fine with Alpha 83:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::mastodon/*"
            ]
        }
    ]
}

```

**To Reproduce**
1. Set this custom policy in Alpha 83
2. Navigate through Mastodon
3. Upgrade to Alpha 84
4. See no media anymore

**Expected behavior**
Expect media to be displayed properly, here with Alpha 83 (blurred by me):

Image

**Actual behavior with Alpha 84**

Image

**Additions**
The error-log shows nothing, all the logs are in the normal rustfs-log:

```bash
{"timestamp":"2026-03-01T21:12:46.347196405+01:00","level":"ERROR","fields":{"message":"op returns error","op":"GetObject","err":"S3Error(Inner { code: AccessDenied, message: Some(\"Access Denied\"), request_id: None, status_code: None, source: None, headers: None })"},"target":"s3s::ops","filename":"/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/s3s-0.13.0/src/ops/mod.rs","line_number":247,"threadName":"rustfs-worker","threadId":"ThreadId(25)"}
{"timestamp":"2026-03-01T21:12:46.34912322+01:00","level":"WARN","fields":{"message":"Failed to propagate tracing context: `SpanDisabled`"},"target":"rustfs::server::http","filename":"rustfs/src/server/http.rs","line_number":652,"threadName":"rustfs-worker","threadId":"ThreadId(39)"}
{"timestamp":"2026-03-01T21:12:46.349409262+01:00","level":"ERROR","fields":{"message":"op returns error","op":"GetObject","err":"S3Error(Inner { code: AccessDenied, message: Some(\"Access Denied\"), request_id: None, status_code: None, source: None, headers: None })"},"target":"s3s::ops","filename":"/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/s3s-0.13.0/src/ops/mod.rs","line_number":247,"threadName":"rustfs-worker","threadId":"ThreadId(39)"}


```

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 24.04 ARM64
 - Browser Firefox / Brave
 - Version RustFS Alpha 84

### PR DESCRIPTION
**Pull request by GatewayJ**
## Type of Change
- [ ] New Feature
- [x] Bug Fix
- [ ] Documentation
- [ ] Performance Improvement
- [ ] Test/CI
- [ ] Refactor
- [ ] Other:

## Related Issues
Closes #2036

## Summary of Changes
Fixed anonymous access being incorrectly denied when no `PublicAccessBlock` configuration exists on a bucket.

Commit `f0c5d76` (PR #2033) introduced a `RestrictPublicBuckets` check for anonymous access. The error handling used a "fail closed" approach that treated **all** errors — including `ConfigNotFound` — as access denial. Since most buckets never have a `PublicAccessBlock` configuration set, `get_public_access_block_config()` returns `Err(ConfigNotFound)`, which was incorrectly mapped to `AccessDenied`.

The fix distinguishes `ConfigNotFound` (no config = no restrictions, per AWS S3 semantics) from real storage errors (still fail closed).

## Checklist
- [x] I have read and followed the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines
- [x] Passed `make pre-commit`
- [ ] Added/updated necessary tests
- [ ] Documentation updated (if needed)
- [ ] CI/CD passed (if applicable)

## Impact
- [ ] Breaking change (compatibility)
- [ ] Requires doc/config/deployment update
- [ ] Other impact:

## Additional Notes
**Workaround for users who cannot upgrade immediately:**

Run `put-public-access-block` with all options set to `false` on affected buckets:

aws s3api put-public-access-block --bucket <bucket-name> \
  --public-access-block-configuration \
  '{"BlockPublicAcls":false,"IgnorePublicAcls":false,"BlockPublicPolicy":false,"RestrictPublicBuckets":false}' \
  --endpoint-url http://<rustfs-endpoint>

### CODE REVIEW

**Comment by overtrue** [comment]
Good fix, this aligns with the compatibility issue in #2036.

Suggestion: please add a regression test for this exact branch in `authorize_request`.

Recommended cases:
1. Anonymous `ListBucket` is allowed by bucket policy, and `PublicAccessBlock` is missing (`ConfigNotFound`) -> request should be allowed.
2. Same setup, but `restrict_public_buckets=true` -> request should be denied (`AccessDenied`).
3. Non-`ConfigNotFound` read error from `get_public_access_block_config()` -> still deny (fail-closed).

Without these tests, this behavior can regress again easily when auth logic is refactored.

File: rustfs/src/storage/access.rs [hunk 1]
```diff
@@ -473,15 +473,16 @@ pub async fn authorize_request<T>(req: &mut S3Request<T>, action: Action) -> S3R
...
                 match metadata_sys::get_public_access_block_config(bucket_name).await {
                     Ok((config, _)) => {
                         if config.restrict_public_buckets.unwrap_or(false) {
                             return Err(s3_error!(AccessDenied, "Access Denied"));
                         }
                     }
-                    Err(_) => {
-                        return Err(s3_error!(AccessDenied, "Access Denied"));
+                    Err(err) => {
+                        if err != StorageError::ConfigNotFound {
```
Comment (overtrue) [inline rustfs/src/storage/access.rs]: Nice fix. Suggest making the compatibility branch explicit to reduce future regressions:

```rust
Err(StorageError::ConfigNotFound) => {}
Err(_) => {
    return Err(s3_error!(AccessDenied, "Access Denied"));
}
```

This keeps `missing config = legacy default` very clear while preserving fail-closed for other errors.
